<template>
  <v-app dark>
    <div class="text-center fill-height d-flex flex-column align-center mt-p20">
      <div>
        <v-icon color="#f44336" size="100px" class="mb-2 i404">
          mdi-routes
        </v-icon>
      </div>
      <div>
        <h1 v-if="error.statusCode === 404" class="display-1 atl-name">
          {{ pageNotFound }}
        </h1>
        <h1 v-else class="display-1 atl-name">
          {{ otherError }}
        </h1>
      </div>
      <div class="mt-4 text-center">
        <v-btn nuxt to="/" outlined>
          Home page
        </v-btn>
      </div>
    </div>
  </v-app>
</template>

<script>
export default {
  layout: 'empty',
  props: {
    error: {
      type: Object,
      default: null
    }
  },
  data () {
    return {
      pageNotFound: '404 Not Found',
      otherError: 'An error occurred'
    }
  },
  head () {
    const title =
      this.error.statusCode === 404 ? this.pageNotFound : this.otherError
    return {
      title
    }
  }
}
</script>

<style>
.i404 {
  -webkit-animation: scale-up-bottom 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 100ms both;
  animation: scale-up-bottom 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) 100ms both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-5-28 11:19:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-bottom
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-bottom {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }
}

@keyframes scale-up-bottom {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }
}

</style>
